### ISSUE TITLE
Skybell door bell not showing up in devices

### ISSUE THREAD

**Issue by khayamgondal** [pyalarmdotcom/alarmdotcom#276]
I can see skybell on alarm.com app but this device is not showing up in HACS integration

**Comment by elahd** [comment]
Do you have a Skybell HD, or a different Skybell?

**Comment by khayamgondal** [comment]
I have Alarm.com Skybell Slim Line Doorbell Camera (Bronze)
https://www.amazon.com/Alarm-com-Skybell-Doorbell-Camera-Bronze/dp/B072BT9VSH/ref=asc_df_B072BT9VSH/?tag=hyprod-20&linkCode=df0&hvadid=642124052140&hvpos=&hvnetw=g&hvrand=17040966366619873526&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9028317&hvtargid=pla-1456666662848&psc=1&gclid=Cj0KCQjw98ujBhCgARIsAD7QeAj3dMYZT1P0q-h7wpN7pc9YJD_8by82cgk9lIegiAn1vZRzkYV5nHkaAtlJEALw_wcB

**Comment by jprasm** [comment]
Same issue for me. SkyBell ADC-VDB105. No entity exists for it in HA.
Provider is Bell (Canada).

**Comment by elahd** [comment]
Got it. The integration only supports the Skybell HD, and only for changing some settings. It doesn't support video for the HD. 

That was a complicated integration to build -- someone gave me temporary access to their Alarm.com account to build that out.

**Comment by elahd** [comment]
Can you post both a screenshot and the source code (right click -> view page source) of the Alarm.com settings page for your Skybell? If it's the same as the HD, this may be easy. If not, consider whether you're prepared to share access to your doorbell with an internet stranger 😱.

**Comment by jprasm** [comment]
This?
[Screenshot 2023-05-31 at 14.59.55.png copy.pdf](https://github.com/pyalarmdotcom/alarmdotcom/files/11618021/Screenshot.2023-05-31.at.14.59.55.png.copy.pdf)

**Comment by khayamgondal** [comment]
you have to visit alarm.com, sign in, to to settings page, right click in
chrome browser and click view source

**Comment by jprasm** [comment]
yeah, but you're an internet stranger!

**Comment by jprasm** [comment]
elahd, how do i get you what you need for this without compromising my personal info & security? I do not fully understand exactly what data I will be posting here, and what personal information will be exposed.

**Comment by elahd** [comment]
If that doesn't get me enough info, we can talk about how to share access. For what it's worth, support for the Skybell HD was only possible due to an account share (#122). @lutzky was able to share access just to his doorbell, and just to the settings (no video). We should be able to add your model without sharing access, though, considering that the settings pages look so similar.

For extra credit, I can try to support getting notified in HA when the doorbell rings or detects motion. If you want to help with that, run `adc -d -u "YOUR_USERNAME" -p "YOUR_PASSWORD" stream`. Post the data for both motion / push events (everything between `==[ WEBSOCKET MESSAGE: BEGIN ]==` and `==[ WEBSOCKET MESSAGE: END ]==`).

**Comment by elahd** [comment]
Closing as stale. Feel free to reopen if you can pull the info above.
