### ISSUE TITLE
Camera & thermostat support

### ISSUE THREAD

**Issue by shawnshyguy** [pyalarmdotcom/alarmdotcom#50]
Hi,
Currently with ADC, the things I use most are camera feeds (indoor cam + doorbell cam) and thermostat control.
I'm not sure how much of this can be done without a proper API, but any way to get camera feeds and / or thermostat controls would be great. Thanks!

**Comment by uvjustin** [comment]
I don't have my cameras or thermostat through ADC, so I won't be able to add any thing myself. Happy to look at any PRs that add this functionality.
However, if you have the option I would recommend integrating everything directly through HA instead of going through ADC and only use ADC for the alarm functionality. I think that makes the most sense as HA is a much more powerful home automation tool than ADC, and that's what most users do.
ADC's strength is its core product, alarm systems. The system doesn't change very much so it's more stable and reliable (nothing will break on updates), plus the pathway is more reliable as it's over a cell network (although you are dependent on ADC's cloud uptime/reliability, that's most likely better than your home internet and HA server).
I'll leave this open for a while in case anyone else is interested in chiming in or contributing a PR, but I'll close it at a later date if there's no progress.

**Comment by vegardengen** [comment]
@shawnshyguy if you want to take a stab at it, have a look at my PR, [https://github.com/uvjustin/alarmdotcom/pull/56](https://github.com/uvjustin/alarmdotcom/pull/56)

You also need the corresponding [https://github.com/uvjustin/pyalarmdotcomajax/pull/12/](https://github.com/uvjustin/pyalarmdotcomajax/pull/12/)

It is my take at implementing lock support for alarm.com, and I believe it largely outlines at least the scaffolding for supporting other types of properties.

I also have a door bell with camera attached to it, which is provided as part of my alarm system, so I await your PR :)

**Comment by elahd** [comment]
Here's some more info on Alarm.com's camera feeds: https://ahmadnassri.com/blog/alarm-com-camera-vulnerability-exposed/. Looks like they use an MJPEG stream wrapped in encryption. Given the complexity, this is probably best left to someone who owns ADC cameras.

Thermostats are probably easier to implement. @shawnshyguy, if you're down to do some legwork, can you create a new issue for thermostat support using the "[Request support for a new device](https://github.com/uvjustin/alarmdotcom/issues/new/choose)" template? There are instructions in there for providing data that we need to build support for new devices.

**Comment by mjmicks** [comment]
ADC customer here through one of their local distributors...happy to jump on this thread and help in regards to the camera feed support, but will need a bit of guidance as to how to help. I've got a doorbell camera, outdoor camera, as well as an indoor camera that I'd love to tie into my HA setup...

**Comment by AritroSaha10** [comment]
> can you create a new issue for thermostat support using the "[Request support for a new device](https://github.com/uvjustin/alarmdotcom/issues/new/choose)" template? There are instructions in there for providing data that we need to build support for new devices.
#101 Let me know if I should add any more information, seems like they use Janus as a WebRTC server? Not sure if it's possible to display a WebRTC stream from another service in home assistant. Though the use of WebRTC may vary between camera models (my issue was for the ADC-V723)

**Comment by elahd** [comment]
Thermostat support has been implemented. Camera support is being tracked in #101.
