### ISSUE TITLE
Add as official integration again?

### ISSUE THREAD

**Issue by AritroSaha10** [pyalarmdotcom/alarmdotcom#92]
I was looking through the ADR docs, and it seems like the [webscraping ADR](https://github.com/home-assistant/architecture/blob/master/adr/0004-webscraping.md) received an amendment a while ago that allows integrations to use webscraping for authentication, which it seem like this integration only does? 

Not completely sure but if so, a pull request could likely be made again to add this integration to the core repo

**Comment by elahd** [comment]
That's right. Also, using unofficial APIs for the rest of the integration is ok: https://github.com/home-assistant/architecture/issues/252#issuecomment-504217336

@uvjustin?

**Comment by uvjustin** [comment]
@elahd First off, thanks for driving this component forward! I haven't had a chance to review the entire refactor or upgrade my own install yet, but it seems like you've added some new features and polish to everything, and additionally you've put a lot of good scaffolding in place for further extension.
As for this issue, at first I was hesitant about this because I had a discussion on the HA discord a few months back regarding webscraping as it applies to another component. The upshot there was that the rules of the ADR are fairly clear but the reasoning behind it is less so. The reasons behind the ADR include having a fragile API and using a large library for scraping - however undocumented APIs are allowed (which may be fragile), and now with the amendment the large scraping libraries are still allowed. It really seems to me that they wanted to move away from webscraping mostly for the other reason - vendors getting unhappy with "official" support in HA. Also, the motivation for the amendment seems to be just to appease MyQ and Tesla users. Tagging @amelchio here because he probably shares these sentiments.
Anyhow, I do think we can try to put this back in to core given that the MyQ integration seems to do things similarly.

**Comment by elahd** [comment]
Closing this out. The Skybell feature uses web scraping, disqualifying this integration from inclusion in core.
